"""
Django settings for proctor project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5s&=q@nq^y-ncl37d7-4v082y5-wn3mp50rzl+_^&cp$%)rsee'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

AUTH_USER_MODEL = 'core.User'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files on Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'core.middleware.ProfileCompletionMiddleware',  # Add profile completion check
    'core.middleware.ExamMonitoringMiddleware',  # Add monitoring cleanup middleware
]


# Session Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_NAME = 'proctorsessionid'  # Custom session cookie name

# CSRF Settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_AGE = 3600  # 1 hour
CSRF_COOKIE_NAME = 'proctorcsrftoken'

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = 'proctor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.student_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'proctor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



import os
ENV = os.environ.get("ENV", "local")

if ENV != 'render':
    # Local development - MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'proctor_db',
            'USER': 'root',
            'PASSWORD': '6640',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }
else:
    # Production on Render - PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URL for @login_required decorator
LOGIN_URL = 'login'

# Exam Monitoring Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'exam_monitoring_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'exam_monitoring.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'exam_monitoring': {
            'handlers': ['exam_monitoring_file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Email Configuration (SMTP)
# Load SMTP credentials from JSON file
from core.config import smtp_credentials

# Use Brevo HTTP API for production (bypasses SMTP port blocking), Gmail for local development
if ENV == 'render':
    # Brevo HTTP API Configuration for Render (free tier: 300 emails/day)
    # Uses HTTP API instead of SMTP to avoid port blocking issues
    EMAIL_BACKEND = 'core.brevo_backend.BrevoEmailBackend'
    # IMPORTANT: Use verified sender email from Brevo dashboard
    DEFAULT_FROM_EMAIL = os.environ.get('FROM_EMAIL', 'meghmodi4ever@gmail.com')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    SITE_URL = 'https://smartfaceproctor.onrender.com'
    EMAIL_TIMEOUT = 10  # 10 second timeout
    
    # Debug: Print email configuration on startup
    brevo_api_key = os.environ.get('BREVO_API_KEY', '')
    print("=" * 50)
    print("📧 EMAIL CONFIGURATION (RENDER/BREVO HTTP API)")
    print(f"   ENV: {ENV}")
    print(f"   EMAIL_BACKEND: core.brevo_backend.BrevoEmailBackend")
    print(f"   BREVO_API_KEY SET: {bool(brevo_api_key)}")
    print(f"   BREVO_API_KEY LENGTH: {len(brevo_api_key) if brevo_api_key else 0}")
    print(f"   DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
    if not brevo_api_key:
        print("   ⚠️  WARNING: BREVO_API_KEY environment variable is NOT SET!")
        print("   ⚠️  Emails will NOT be sent. Add BREVO_API_KEY in Render Dashboard.")
    else:
        print("   ✅ Brevo API configured - using HTTP API (no SMTP)")
    print("=" * 50)
else:
    # Gmail Configuration for Local Development
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = smtp_credentials.get('SMTP_HOST', 'smtp.gmail.com')
    EMAIL_PORT = smtp_credentials.get('SMTP_PORT', 587)
    EMAIL_USE_TLS = smtp_credentials.get('EMAIL_USE_TLS', True)
    EMAIL_USE_SSL = smtp_credentials.get('EMAIL_USE_SSL', False)
    EMAIL_HOST_USER = smtp_credentials.get('SMTP_USER', '')
    EMAIL_HOST_PASSWORD = smtp_credentials.get('SMTP_API_KEY', '')
    DEFAULT_FROM_EMAIL = smtp_credentials.get('FROM_EMAIL', 'Smart Face Proctor <noreply@proctorsystem.com>')
    SERVER_EMAIL = EMAIL_HOST_USER
    SITE_URL = 'http://localhost:8000'
    
    # Debug: Print email configuration on startup
    print("=" * 50)
    print("📧 EMAIL CONFIGURATION (LOCAL/GMAIL)")
    print(f"   ENV: {ENV}")
    print(f"   EMAIL_HOST: {EMAIL_HOST}")
    print(f"   EMAIL_PORT: {EMAIL_PORT}")
    print(f"   EMAIL_HOST_USER: {EMAIL_HOST_USER[:5]}***" if EMAIL_HOST_USER else "   EMAIL_HOST_USER: NOT SET")
    print(f"   EMAIL_HOST_PASSWORD SET: {bool(EMAIL_HOST_PASSWORD)}")
    print(f"   DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")
    print("=" * 50)

# Create logs directory if it doesn't exist
import os
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
