from django.urls import path
from . import views
from . import admin_views

urlpatterns = [
    path('', views.home_redirect, name='home_redirect'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('forget/', views.forget, name='forget'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('test-otp/', views.test_otp_system, name='test_otp'),
    path('check-db/', views.check_database, name='check_database'),
    path('check-migration/', views.check_migration, name='check_migration'),
    path('video_feed/', views.video_feed, name='video_feed'),
    path('exam_proctoring/', views.exam_proctoring_page, name='exam_proctoring'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
    path('dashboard/faculty/', views.faculty_dashboard, name='faculty_dashboard'),
    path('dashboard/faculty/exams/', views.faculty_exams, name='faculty_exams'),
    path('dashboard/faculty/schedule/', views.schedule_exam_page, name='schedule_exam_page'),
    path('dashboard/faculty/preview/', views.schedule_exam_preview, name='schedule_exam_preview'),
    path('dashboard/faculty/profile/', views.faculty_profile, name='faculty_profile'),
    path('student/exams/', views.student_exams, name='student_exams'),
    path('student/profile/', views.student_profile, name='student_profile'),
    path('student/start-exam/<int:exam_id>/', views.start_exam, name='start_exam'),
    path('student/mcq-exam/<int:exam_id>/', views.mcq_exam, name='mcq_exam'),
    path('student/start-mcq-exam/<int:exam_id>/', views.start_mcq_exam, name='start_mcq_exam'),
    path('student/submit-exam/<int:exam_id>/', views.submit_exam, name='submit_exam'),
    path('student/exam-instructions/<int:exam_id>/', views.exam_instructions, name='exam_instructions'),
    path('student/exam-results/<int:exam_id>/', views.exam_results, name='exam_results'),
    path('student/exam-review/<int:exam_id>/', views.exam_review, name='exam_review'),
    path('report-bug/', views.report_bug, name='report_bug'),
    path('schedule_exam/', views.schedule_exam, name='schedule_exam'),
    path('delete_exam/<int:exam_id>/', views.delete_exam, name='delete_exam'),
    
    # Custom Admin URLs
    path('customadmin/login/', admin_views.admin_login, name='admin_login'),
    path('customadmin/logout/', admin_views.admin_logout, name='admin_logout'),
    path('customadmin/dashboard/', admin_views.admin_dashboard, name='admin_dashboard'),
    path('customadmin/users/', admin_views.admin_users, name='admin_users'),
    path('customadmin/users/import/', admin_views.admin_import_users, name='admin_import_users'),
    path('customadmin/users/create/', admin_views.admin_user_create, name='admin_user_create'),
    path('customadmin/users/<int:user_id>/', admin_views.admin_user_detail, name='admin_user_detail'),
    path('customadmin/exams/', admin_views.admin_exams, name='admin_exams'),
    path('customadmin/exams/create/', admin_views.admin_exam_create, name='admin_exam_create'),
    path('customadmin/exams/<int:exam_id>/', admin_views.admin_exam_detail, name='admin_exam_detail'),
    path('customadmin/exams/<int:exam_id>/assignments/', admin_views.admin_exam_assignments, name='admin_exam_assignments'),
    path('customadmin/submissions/', admin_views.admin_submissions, name='admin_submissions'),
    path('customadmin/violations/', admin_views.admin_violations, name='admin_violations'),
    path('customadmin/bugs/', admin_views.admin_bug_reports, name='admin_bug_reports'),
    path('customadmin/bugs/<int:bug_id>/', admin_views.admin_bug_detail, name='admin_bug_detail'),
    path('customadmin/settings/', admin_views.admin_system_settings, name='admin_system_settings'),
    path('customadmin/export/', admin_views.admin_export_data, name='admin_export_data'),
]