# Generated by Django 5.2.3 on 2025-08-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_selective',
            field=models.BooleanField(default=False, help_text='If True, only assigned students can take this exam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Admin', 'Admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'role__in': ['Faculty', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
