# Generated by Django 5.2.5 on 2025-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_exam_is_selective_alter_user_role_examassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='absence_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='warning_limit',
            field=models.IntegerField(default=3),
        ),
    ]
