# Generated by Django 5.2.5 on 2025-10-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_options_remove_user_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_on',
            new_name='created_at',
        ),
    ]
