# Generated by Django 5.2.5 on 2025-10-29 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_submitted_on_submission_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='created_at',
            new_name='submitted_on',
        ),
        migrations.AddField(
            model_name='violation',
            name='freeze_cancelled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_freezes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violation',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='violation',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.exam'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='type',
            field=models.CharField(choices=[('Distraction', 'Distraction'), ('Face Missing', 'Face Missing'), ('Multiple Faces', 'Multiple Faces'), ('Warning Limit Exceeded', 'Warning Limit Exceeded'), ('Looking Away', 'Looking Away')], max_length=50),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_reattempt', models.BooleanField(default=False)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exam')),
                ('reset_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'Faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_resets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
