# Generated by Django 5.2.5 on 2025-10-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_division_user_division_semester_division_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.semester'),
        ),
    ]
