# Generated by Django 5.2.5 on 2025-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_examattempt_ended_at_alter_user_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violation',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
