# Generated by Django 5.2.5 on 2025-11-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
