# Generated by Django 5.2.5 on 2025-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notificationread_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when exam was created', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, help_text='Date when profile was first completed', null=True),
        ),
    ]
